# Collinear PDF set
pdfset:
  name: "MMHT2014nlo68cl"
  member: 0

# Collinear FF set
ffset:
  name: "DSS14_NLO_PiSum"
  member: 0

# Perturbative order
PerturbativeOrder: 2

# Initial and final scale-variation factors
TMDscales:
  Ci: 1
  Cf: 1

# Values of 'bmin' and 'bmax' required by the b* prescription
bstar:
  bmin: 0
  bmax: 1

# Reference value of alpha_em
alphaem:
  aref: 0.00776578395589
  Qref: 91.1876
  run: true

# Parameters of the x-space subgrid on which collinear PDFs are
# tabulated
xgridpdf:
  - [50, 1e-3, 3]
  - [60, 1e-1, 3]
  - [50, 6e-1, 3]
  - [50, 8e-1, 3]

# Parameters of the x-space subgrid on which collinear FFs are
# tabulated
xgridff:
  - [60, 1e-2, 3]
  - [50, 6e-1, 3]
  - [50, 8e-1, 3]

# Maximum number of Ogata-quadrature points (no more than 1000)
nOgata: 100

# Number of points, interpolation degree, and integration accuracy
# of the grid in Q
Qgrid:
  n: 5
  InterDegree: 1
  eps: 1e-3

# Number of points, interpolation degree, and integration accuracy
# of the grid in xi
xigrid:
  n: 5
  InterDegree: 1
  eps: 1e-3
