Description: PV17qGauss
Minimiser: none
Seed: '1234'
qToQmax: '0.2'
t0prescription: true
Parameterisation: PV19
t0parameters:
- 0.02986
- 3.8486
- 18.5075
- 4.938
- 0.0
- 0.8407
- 0.7921
- 62.473
- 4.075
- 0.0
- 0.0
- 0.1
- 0.01781
- 2.0
Parameters:
- name: g2
  starting_value: 0.02986
  step: 0.05
  fix: false
- name: N1
  starting_value: 3.8486
  step: 0.05
  fix: false
- name: alpha
  starting_value: 18.5075
  step: 0.5
  fix: false
- name: sigma
  starting_value: 4.938
  step: 0.1
  fix: false
- name: delta
  starting_value: 0.0
  step: 0.02
  fix: true
- name: lambdaB
  starting_value: 0.8407
  step: 0.05
  fix: false
- name: N1B
  starting_value: 0.7921
  step: 0.05
  fix: false
- name: alphaB
  starting_value: 62.47
  step: 0.5
  fix: false
- name: sigmaB
  starting_value: 4.075
  step: 0.1
  fix: false
- name: deltaB
  starting_value: 0.0
  step: 0.02
  fix: true
- name: lambdaC
  starting_value: 0.0
  step: 0.1
  fix: true
- name: g1C
  starting_value: 0.1
  step: 0.05
  fix: true
- name: g2B
  starting_value: 0.01781
  step: 0.05
  fix: false
- name: qq
  starting_value: 2.
  step: 0.05
  fix: true
