Description: AleLambda3
Minimiser: ceres
Seed: 1234
qToQmax: 0.2
t0prescription: true
Parameterisation: PV19
t0parameters:
  - 0.032378
  - 0.387946
  - 3.2012136
  - 0.78818279
  - 0
  - 0.5
Parameters:
  - name: g2
    starting_value: 0.082741059
    step: 0.01
    fix: false
  - name: N1
    starting_value: 1.0106413
    step: 0.03
    fix: false
  - name: alpha
    starting_value: 6.0044507
    step: 0.1
    fix: false
  - name: sigma
    starting_value: 1.2031182
    step: 0.05
    fix: false
  - name: lambda
    starting_value: 1.173496
    step: 0.05
    fix: false
  - name: delta
    starting_value: 0.096467526
    step: 0.02
    fix: false
