Description: AleLambda3
Minimiser: ceres
Seed: 1234
qToQmax: 0.2
t0prescription: true
Parameterisation: PV19
t0parameters:
  - 0.032378
  - 0.387946
  - 3.2012136
  - 0.78818279
  - 0
  - 0.5
Parameters:
  - name: g2
    starting_value: 0.09508584
    step: 0.01
    fix: false
  - name: N1
    starting_value: 0.76328129
    step: 0.03
    fix: false
  - name: alpha
    starting_value: 5.1494143
    step: 0.1
    fix: false
  - name: sigma
    starting_value: 1.5210254
    step: 0.05
    fix: false
  - name: lambda
    starting_value: 0.52752979
    step: 0.05
    fix: false
  - name: delta
    starting_value: 0.1425194
    step: 0.02
    fix: false
