# Name of the collinear PDF set
pdfset:
  name: "MMHT2014nlo68cl"
  member: 0

# Perturbative order
PerturbativeOrder: 1

# Initial and final scale-variation factors
TMDscales:
  Ci: 1
  Cf: 1

# Values of 'bmin' and 'bmax' required by the b* prescription
bstar:
  bmin: 0
  bmax: 1

# Maximum number of Ogata-quadrature points (no more than 1000)
nOgata: 10

# Parameters of the x-space subgrid on which collinear PDFs are
# tabulated
xgridpdf:
  - [50, 1e-3, 3]
  - [60, 1e-1, 3]
  - [50, 6e-1, 3]
  - [50, 8e-1, 3]

# Number of points and interpolation degree of the grid in Q
Qgrid:
  nQ: 5
  InterDegreeQ: 1

# Number of points and interpolation degree of the grid in xi ( = exp(y))
xigrid:
  nxi: 5
  InterDegreexi: 1

# Accuracy of the gauss-quadrature integration used of the integrals
# in Q and xi.
integration_accuracy: 1e-3

# Verbosity level of APFEL++.
verbosity: 2
