Description: 'Scan around the minimum of fitPV19_2nd. This is the output of Minuit2.'
Minimiser: scan
Seed: '1234'
qToQmax: '0.2'
Error function cut: '4'
t0prescription: true
Paramfluct: false
Parameterisation: PV19
Parameters:
- name: $g_2$
  starting_value: 0.01395550210504
  step: 0.01419673181475
  fix: false
- name: $N_1$
  starting_value: 2.793035171873
  step: 1.413582213765
  fix: false
- name: $\alpha$
  starting_value: 21.42155062249
  step: 8.051294836362
  fix: false
- name: $\sigma$
  starting_value: 5.580717215756
  step: 2.394371467483
  fix: false
- name: $\delta$
  starting_value: 0.0
  step: 0.00
  fix: true
- name: $\lambda_B$
  starting_value: 0.7908312504393
  step: 0.05790555538672
  fix: false
- name: $N_{1,B}$
  starting_value: 0.9110798699983
  step: 0.4586084000651
  fix: false
- name: $\alpha_B$
  starting_value: 60.98167621649
  step: 21.48798960477
  fix: false
- name: $\sigma_B$
  starting_value: 3.795919789581
  step: 1.417417473514
  fix: false
- name: $\delta_B$
  starting_value: 0.0
  step: 0.00
  fix: true
- name: $\lambda_C$
  starting_value: 0.0
  step: 0.0
  fix: true
- name: $g_{1,C}$
  starting_value: 0.1
  step: 0.0
  fix: true
- name: $g_{2,B}$
  starting_value: 0.01652426301925
  step: 0.004077023417563
  fix: false
- name: $\beta$
  starting_value: 2.0
  step: 0.0
  fix: true

## The result of the fit with the configuration reported above is:
# Total chi2 = 1.1285


# The values in this file are taken from a previous minimisation that had this output:
#### Minuit output:

# # ext. ||   Name    ||   type  ||     Value     ||  Error +/-
#
#    0   ||     $g_2$ ||  free   ||    0.01395550210504 ||0.01419673181475
#    1   ||     $N_1$ ||  free   ||      2.793035171873 ||1.413582213765
#    2   ||  $\alpha$ ||  free   ||      21.42155062249 ||8.051294836362
#    3   ||  $\sigma$ ||  free   ||      5.580717215756 ||2.394371467483
#    4   ||  $\delta$ ||  fixed  ||                   0 ||
#    5   ||$\lambda_B$ ||  free   ||     0.7908312504393 ||0.05790555538672
#    6   || $N_{1,B}$ ||  free   ||     0.9110798699983 ||0.4586084000651
#    7   ||$\alpha_B$ ||  free   ||      60.98167621649 ||21.48798960477
#    8   ||$\sigma_B$ ||  free   ||      3.795919789581 ||1.417417473514
#    9   ||$\delta_B$ ||  fixed  ||                   0 ||
#   10   ||$\lambda_C$ ||  fixed  ||                   0 ||
#   11   || $g_{1,C}$ ||  fixed  ||                 0.1 ||
#   12   || $g_{2,B}$ ||  free   ||    0.01652426301925 ||0.004077023417563
#   13   ||   $\beta$ ||  fixed  ||                   2 ||
#
# Total chi2 = 1.1285
t0parameters: [0.015552, 1.0, 21.25188, 5.617127, 0.0, 0.814108, 0.1, 40.62831, 3.024931,
  0.0, 0.0, 0.1, 0.017413, 2.0]
